### ISSUE TITLE
wrong date or day of week

### ISSUE THREAD

**Issue by azaharov88** [dev-charles15531/v3-events-calendar#4]
![image](https://github.com/user-attachments/assets/9439af26-2f6c-41dc-8707-9c9c06a79f72)
08 October 2024 is Tuesday but showing wednesday

**Comment by dev-charles15531** [comment]
That was a timezone issue, and has been fixed.
Thanks for this.

**Comment by azaharov88** [comment]
![image](https://github.com/user-attachments/assets/d1e5057e-ca1a-4f65-89d1-120e793dcc4f)
Thanks for fixing, I'd update component, but still see error, 10 Oct is Tuesday, not Friday. How could I fix that? And one more, could you tell me, how to change start week since monday?

**Comment by dev-charles15531** [comment]
![Screenshot from 2024-10-10 10-49-44](https://github.com/user-attachments/assets/a29982b7-b5e9-4f08-9261-3a57825b9f99)

Everything seems okay here. Did you update the npm package?

**Comment by dev-charles15531** [comment]
I will make an update to the package and expose props so week can start from either Monday or Sunday

**Comment by azaharov88** [comment]
> ![Screenshot from 2024-10-10 10-49-44](https://private-user-images.githubusercontent.com/68998548/375322542-a29982b7-b5e9-4f08-9261-3a57825b9f99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NTQyMzksIm5iZiI6MTcyODU1MzkzOSwicGF0aCI6Ii82ODk5ODU0OC8zNzUzMjI1NDItYTI5OTgyYjctYjVlOS00ZjA4LTkyNjEtM2E1NzgyNWI5Zjk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA5NTIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNzQwMmRlMzAyNTVlN2E1ZDRjOTcyZmNmM2ZlNmNkYzE3YWZhZjFkZWQ5NWUwMGRhOWIwMWZlZTE3NjE2ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.raNeEdAtMsZJvC_ztpq8mAK3AueLN5RPEHSD4LiMCEQ)
> 
> Everything seems okay here. Did you update the npm package?

yep, package updated, after update i saw new png files in directory. Ok I'll try to reinstall it
![image](https://github.com/user-attachments/assets/0652494f-d6a2-401a-9d06-93227a9f128f)

**Comment by azaharov88** [comment]
![image](https://github.com/user-attachments/assets/e53ca7b2-b04c-49c6-9ace-859218aa2049)
reinstall and still got wrong date((. We are in N. Central Asia Standard Time +7 timezone, how can i fix that ussue? And patiently wait new update to change start a week)))

**Comment by dev-charles15531** [comment]
Alright. 

Would jump on it to make update so you can pass a timezone prop, as well as "Monday" as first day of the week

**Comment by dev-charles15531** [comment]
@azaharov88 

The package has been updated and you can now pass a prop to set if the calendar's first day of the week is Sunday or Monday, and you can also pass an optional timezone prop of your current timezone

**Comment by azaharov88** [comment]
After package update  cannot build project, got this:
build started...
✓ 10 modules transformed.
[commonjs--resolver] Failed to resolve entry for package "v3-events-calendar". The package may have incorrect main/module/exports specified in its package.json.
It happens cause in v3-events-calendar no dist directory with it's files, even if remove and install it again
![image](https://github.com/user-attachments/assets/5601b765-e777-42a1-b971-e2556a485bfe)

**Comment by dev-charles15531** [comment]
Let me check  and see if i can reproduce

**Comment by dev-charles15531** [comment]
@azaharov88 

A new update has been published and patched.
Thank you!

**Comment by azaharov88** [comment]
Works fine! You're great! Realy thanks!

**Comment by azaharov88** [comment]
If you want to make greater component, would be nice to make a locale file with names of months, days etc.

**Comment by azaharov88** [comment]
Got another issue after update))))  events popup don't open in after clicking. No errors in console
![image](https://github.com/user-attachments/assets/bffb5b81-5703-4e99-93b3-ac77f4ffe2f9)

**Comment by dev-charles15531** [comment]
Can you show your code?
parts of it related to the calendar so i can see if you're doing anything incorrectly.

Popups works just fine on my end.

**Comment by dev-charles15531** [comment]
> If you want to make greater component, would be nice to make a locale file with names of months, days etc.

I don't understand what you mean

**Comment by azaharov88** [comment]
> > If you want to make greater component, would be nice to make a locale file with names of months, days etc.
> 
> I don't understand what you mean

I mean, make locale files so you can changing language just by changing locale

**Comment by azaharov88** [comment]
> Can you show your code? parts of it related to the calendar so i can see if you're doing anything incorrectly.
> 
> Popups works just fine on my end.

Sorry, forget it, it's not part of calendar code)
